name: Release Please

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '.github/cli-release-please.yml'
  workflow_dispatch: {}

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Release Please (manifest)
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
