[package]
name = "@mattheu/cli"
version = "0.0.0"
description = "Extracted AI context package"
license = "MIT"

[exports.codex]
template = "templates/AGENTS.md.hbs"
mcpServers = "templates/codex/mcp_servers.toml.hbs"

[exports.claude]
template = "templates/CLAUDE.md.hbs"
subagentsDir = "templates/claude/agents"
mcpServers = "templates/claude/mcp_servers.json.hbs"

[exports.cursor]
template = "templates/cursor.rules.hbs"

[metadata]
tz_spec_version = 1
