name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js (from .nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Check formatting
        run: pnpm run format:check

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm test

      - name: Smoke test
        run: node dist/tz.mjs --help

      - name: Upload CLI bundle
        uses: actions/upload-artifact@v4
        with:
          name: tz-mjs-${{ runner.os }}-${{ runner.arch }}
          path: dist/tz.mjs
          if-no-files-found: error

  sea-build:
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js (from .nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build bundle
        run: pnpm run build

      - name: SEA build + run
        run: pnpm run test:sea

      - name: Upload SEA artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tz-sea-${{ runner.os }}-${{ runner.arch }}
          path: |
            dist/tz-sea*
            dist/sea-prep.blob
          if-no-files-found: warn

  sea-blob-pr:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js (from .nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build bundle
        run: pnpm run build

      - name: SEA blob (no inject)
        run: pnpm run test:sea -- --blob
