name: CI

on:
  push:
    branches: [main, master]
    paths:
      - 'cli/**'
      - '.github/workflows/cli-ci.yml'
  pull_request:
    branches: [main, master]
    paths:
      - 'cli/**'
      - '.github/workflows/cli-ci.yml'

jobs:
  build-and-test:
    # Simplified to single Ubuntu job: lint, build, test only
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node.js (from .nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: cli/.nvmrc
          cache: 'pnpm'
          cache-dependency-path: cli/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Check formatting
        run: pnpm run format:check
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm test
